const errorsEnum = {
  SERVER_ERROR: 'SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_OR_PASS_IS_WRONG: 'EMAIL_OR_PASS_IS_WRONG',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  MONO_API_ERROR: 'MONO_API_ERROR',
  INVALID_OBJ_ID: 'INVALID_OBJ_ID',
};

module.exports = Object.freeze(errorsEnum);
